name: Reusable e2e workflow for API

on:
  workflow_call:
    inputs:
      path:
        description: "sub-directory where this workflow should execute lint and build "
        required: false
        type: string
        default: "packages/api"
    secrets:
      TEST_API_KEY:
        required: true

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run test
        working-directory: ${{ inputs.path }}
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
