name: Reusable e2e workflow for API

on:
  workflow_call:
    secrets:
      TEST_API_KEY:
        required: true

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run test
        working-directory: ${{ inputs.path }}
