name: Reusable e2e workflow for API

on:
  workflow_call:
    inputs:
      path:
        description: "sub-directory where this workflow should execute lint and build "
        required: false
        type: string
        default: "packages/api"
      deploy_env:
        description: "the environment we're deploying to, either 'staging', 'production', or 'sandbox'"
        required: true
        type: string
    secrets:
      TEST_API_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    workflow_dispatch: # manually executed by a user

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    steps:
      - name: Log Environment
        run: |
          env
          echo "ECR_REPO_URI: ${{ inputs.ECR_REPO_URI }}"
          echo "ECS_CLUSTER: ${{ inputs.ECS_CLUSTER }}"
          echo "ECS_SERVICE: ${{ inputs.ECS_SERVICE }}"
          echo "AWS_REGION: ${{ inputs.AWS_REGION }}"
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log Git Ref
        run: |
          echo "Git ref: $(git rev-parse HEAD)"
        shell: bash

      - name: Install dependencies
        run: npm run install-deps
        working-directory: "./"

      - name: Build/compile
        # build from root because of dependencies
        run: npm run build:cloud
        working-directory: "./"

      - name: Run Tests
        run: npm run test
        working-directory: ${{ inputs.path }}
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
