name: Reusable Release script

on:
  workflow_call: # called by other workflows
  workflow_dispatch: # manually executed by a user - should be able to remove this once semver is well mature

# From https://thecodinganalyst.github.io/knowledgebase/Using-Semantic-Release-with-Github-Actions/
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          npx semantic-release
