name: A WIP test E2E trigger

on:
  workflow_dispatch: # manually executed by a user
    inputs:
      theJob:
        type: choice
        description: Outbound or Inbound servers?
        options:
          - blue
          - green
          - both
        required: true

jobs:
  blue:
    if: ${{ inputs.theJob == 'blue' || inputs.theJob == 'both' }}
    runs-on: ubuntu-latest
    steps:
      - name: Blue
        run: |
          env
          echo "Running Blue"
        shell: bash

  green:
    if: ${{ inputs.theJob == 'green' || inputs.theJob == 'both' }}
    runs-on: ubuntu-latest
    steps:
      - name: Green
        run: |
          env
          echo "Running Green"
        shell: bash

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [blue, green]
    # run even if one of the dependencies didn't
    # can't use ${{ ! failure() && success() }} because `success()` "Returns true when none of the previous steps have failed or been canceled."
    # can't use ${{ ! failure() && contains(needs.*.result, 'success') }} because if anything that came before succeeded, even if not a direct dependency, it will run
    # if: ${{ !failure() && (needs.api-sandbox.result == 'success' || needs.infra-api-lambdas-sandbox.result == 'success' || needs.infra-ihe-gw.result == 'success' || needs.ihe-gw-server.result == 'success') }}
    steps:
      - name: E2E Tests
        run: |
          env
          echo "Running E2E tests!"
        shell: bash
