name: API/Lambdas Deploy - PRODUCTION

on:
  push:
    branches:
      - master
    paths:
      - 'api/app/**'
      - 'api/lambdas/**'
  workflow_dispatch:

jobs:
  production-build:
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "api/app" # there's no "build" for lambdas, so one job for both works

  production-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: production-build
    with:
      deploy_env: "production"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.API_REGION_PRODUCTION }}
      CDK_STACK: ${{ secrets.API_STACK_NAME_PRODUCTION }}

  sandbox-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: production-deploy
    with:
      deploy_env: "sandbox"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.API_REGION_SANDBOX }}
      CDK_STACK: ${{ secrets.API_STACK_NAME_SANDBOX }}
