name: Branch to Staging

# Used to manually deploy a branch to staging

on:
  workflow_dispatch: # manually executed by a user

jobs:
  widget-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    with:
      build_env: "staging"
      deploy_env: "staging"
      cdk_stack: ${{ vars.WIDGET_STACK_NAME_STAGING }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.WIDGET_REGION_STAGING }} # renamed
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_STAGING }} # renamed
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  api-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    with:
      deploy_env: "staging"
      cdk_stack: ${{ vars.API_STACK_NAME_STAGING }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.API_REGION_STAGING }} # renamed
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_STAGING }} # renamed
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
