name: Branch to Staging

# Used to manually deploy a branch to staging

on:
  workflow_dispatch: # manually executed by a user

jobs:
  widget-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    with:
      build_env: "staging"
      deploy_env: "staging"
      cdk_stack: ${{ vars.WIDGET_STACK_NAME_STAGING }}
    secrets: inherit


  api-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    with:
      deploy_env: "staging"
      cdk_stack: ${{ vars.API_STACK_NAME_STAGING }}
    secrets: inherit
