name: Deploy - Staging

on:
  push: # a commit to the specified branches, if any
    branches:
      - develop
    paths:
      - "connect-widget/**"
      - "api/**"
      - "infra/**"
      - "package*.json"
  workflow_dispatch: # manually executed by a user

jobs:
  files-changed:
    name: detect changes
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # Map a step output to a job output
    outputs:
      api: ${{ steps.changes.outputs.api }}
      lambdas: ${{ steps.changes.outputs.lambdas }}
      widget: ${{ steps.changes.outputs.widget }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Detect Changes
        uses: dorny/paths-filter@4067d885736b84de7c414f582ac45897079b0a78 # v2
        id: changes
        with:
          filters: |
            api:
              - "api/app/**"
              - "infra/**"
              - "package*.json"
            lambdas:
              - "api/lambdas/**"
              - "infra/**"
              - "package*.json"
            widget:
              - "connect-widget/**"
              - "infra/**"
              - "package*.json"

  widget-build:
    if: needs.files-changed.outputs.widget == 'true'
    needs: files-changed
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "connect-widget/app"
      build_env: "staging"
    secrets: inherit
  widget-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: widget-build
    with:
      build_env: "staging"
      deploy_env: "staging"
      cdk_stack: ${{ vars.WIDGET_STACK_NAME_STAGING }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.WIDGET_REGION_STAGING }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_STAGING }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  api-build:
    if: needs.files-changed.outputs.api == 'true'
    needs: files-changed
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "api/app" # there's no "build" for lambdas, so one job for both works
    secrets: inherit
  lambdas-build:
    if: needs.files-changed.outputs.lambdas == 'true'
    needs: files-changed
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "api/lambdas"
      install-from-parent: false
    secrets: inherit
  api-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: [api-build, lambdas-build]
    if: ${{ !failure() && (needs.api-build.result == 'success' || needs.lambdas-build.result == 'success') }}
    with:
      deploy_env: "staging"
      cdk_stack: ${{ vars.API_STACK_NAME_STAGING }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.API_REGION_STAGING }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_STAGING }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  release:
    uses: ./.github/workflows/_reusable_release.yml
    needs: [widget-deploy, api-deploy]
    # run even if one of the dependencies didn't
    # can't use ${{ ! failure() && success() }} because `success()` "Returns true when none of the previous steps have failed or been canceled."
    # can't use ${{ ! failure() && contains(needs.*.result, 'success') }} because if anything that came before succeeded, even if not a direct dependency, it will run
    if: ${{ !failure() && (needs.widget-deploy.result == 'success' || needs.api-deploy.result == 'success') }}
    secrets: inherit
