name: Deploy - PRODUCTION

on:
  push: # a commit to the specified branches, if any
    branches:
      - master
    paths:
      - "connect-widget/app/**"
      - "api/app/**"
      - "api/lambdas/**"
      - "infra/**"
      - 'package.json'
      - '.github/workflows/**'
  workflow_dispatch: # manually executed by a user

jobs:
  widget-build:
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "connect-widget/app"
      build_env: "production"
  widget-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: widget-build
    with:
      build_env: "production"
      deploy_env: "production"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.WIDGET_REGION_PRODUCTION }}
      CDK_STACK: ${{ secrets.WIDGET_STACK_NAME_PRODUCTION }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_PRODUCTION }}

  api-build:
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "api/app" # there's no "build" for lambdas, so one job for both works
  api-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: api-build
    with:
      deploy_env: "production"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.API_REGION_PRODUCTION }}
      CDK_STACK: ${{ secrets.API_STACK_NAME_PRODUCTION }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_PRODUCTION }}
  api-sandbox-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: api-deploy
    with:
      deploy_env: "sandbox"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.API_REGION_SANDBOX }}
      CDK_STACK: ${{ secrets.API_STACK_NAME_SANDBOX }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_SANDBOX }}

  release:
    uses: ./.github/workflows/_reusable_release.yml
    needs: [widget-deploy, api-sandbox-deploy]
    secrets: inherit
