name: PR Check - API SDK

on:
  pull_request:
    paths:
      - "packages/api-sdk/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "packages/api-sdk"
    secrets: inherit
