name: PR Check - API

on:
  pull_request:
    paths:
      - "packages/api/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "packages/api"
    secrets: inherit
