name: PR Check - Utils

on:
  pull_request:
    paths:
      - "utils/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "utils"
      install-from-parent: false
    secrets: inherit
