name: PR Check - Utils

on:
  pull_request:
    paths:
      - "packages/utils/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "packages/utils"
    secrets: inherit
