name: PR Check - Lambdas

on:
  pull_request:
    paths:
      - "api/lambdas/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "api/lambdas/new"
      install-from-parent: false
    secrets: inherit
