name: PR Check - Infra

on:
  pull_request:
    paths:
      - "infra/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "infra"
    secrets: inherit
