name: PR Check - commonwell-jwt-maker

on:
  pull_request:
    paths:
      - "packages/commonwell-jwt-maker/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "packages/commonwell-jwt-maker"
    secrets: inherit
