name: PR Check - Lambdas

on:
  pull_request:
    paths:
      - "packages/lambdas/**"
  merge_group:
  workflow_dispatch:

jobs:
  check-pr:
    uses: ./.github/workflows/_build.yml
    with:
      path: "packages/lambdas"
      install-from-parent: false
    secrets: inherit
