name: Restart IHE GW - Staging

on:
  workflow_dispatch:
    inputs:
      server:
        type: choice
        description: Outbound or Inbound servers?
        options:
        - inbound
        - outbound

jobs:
  restart-outbound:
    if: ${{ inputs.server == 'outbound' }}
    uses: ./.github/workflows/_restart-ecs.yml
    with:
      ECR_REPO_URI: ${{ vars.IHE_ECR_REPO_URI_STAGING }}
      ECS_CLUSTER: ${{ vars.IHE_ECS_CLUSTER_STAGING }}
      ECS_SERVICE: ${{ vars.IHE_OUTBOUND_ECS_SERVICE_STAGING }}
      AWS_REGION: ${{ vars.IHE_REGION_STAGING }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  restart-inbound:
    if: ${{ inputs.server == 'inbound' }}
    uses: ./.github/workflows/_restart-ecs.yml
    with:
      ECR_REPO_URI: ${{ vars.IHE_ECR_REPO_URI_STAGING }}
      ECS_CLUSTER: ${{ vars.IHE_ECS_CLUSTER_STAGING }}
      ECS_SERVICE: ${{ vars.IHE_INBOUND_ECS_SERVICE_STAGING }}
      AWS_REGION: ${{ vars.IHE_REGION_STAGING }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
