name: Widget Deploy - Staging

on:
  push:
    branches:
      - develop
    paths:
      - 'connect-widget/app/**'
  workflow_dispatch:

jobs:
  staging-build:
    uses: ./.github/workflows/_reusable_build.yml
    with:
      path: "connect-widget/app"
      build_env: "staging"

  staging-deploy:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: staging-build
    with:
      build_env: "staging"
      deploy_env: "staging"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.WIDGET_REGION_STAGING }}
      CDK_STACK: ${{ secrets.WIDGET_STACK_NAME_STAGING }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_STAGING }}
